algoritmo "semnome"
// Função :
// Autor :
// Data : 07/06/2022
// Seção de Declarações 
var
   n,valor:real
   resp:inteiro
inicio
      enquanto (resp <> 1111)faca
         escreva ("digite o número a ser somado: ")
         leia (n)
         valor <- valor +n
         escreva ("Digite qualquer número para continuar: ")
         leia (resp)
      fimenquanto
      escreval ("")
      escreval ("A somatoria dos números é: ",valor)
fimalgoritmo
