algoritmo "semnome"

var
   x,y,r:inteiro
funcao  potencial (a,b:inteiro):inteiro
var
   c,n:inteiro
inicio
      n<-a
   para c<-1 ate b faca
      N<-n*a
   fimpara
   R<-n
   retorne R
fimfuncao
inicio
      escreva ("digite o numero: ")
      leia(X)
      escreva ("digite o valor da exponenciação: ")
      leia (Y)
      R <- potencial(x,y)
      escreva (x," elevado a",y," é igual a:",r)
fimalgoritmo
