algoritmo "semnome"

var
   area,r,altura,largura:real
inicio
      escreva ("Qual a altura da parede? ")
      leia (altura)
      escreva ("Qual a largura da parede? ")
      leia (largura)
      area <- largura * altura
      R <- area/2
      escreval ("A area a ser pintada é de:",area," Metros Quadrados")
      escreval ("A quantidade de litros que serão usados é:",R," litros")

fimalgoritmo
