algoritmo "semnome"
// Função :
// Autor :
// Data : 01/06/2022
// Seção de Declarações 
var
   VC,KE:inteiro
   multa: real
inicio
      escreva ("Qual a velocidade do carro? ")
      leia (VC)
      se (vc >80)entao
         KE<- vc-80
         multa <- ke*5
         escreval ("Velocidade acima do permitido, usuario sera multaado em: R$",multa:5:2)
      senao
         escreval ("Parebens a velocidade está dentro dos conformes!")
      fimse
fimalgoritmo
