algoritmo "semnome"

var
   KM,Kmp:real
   DIAS,DiasP:inteiro
inicio
      escreva ("Quantos KM foram percorridos com carro? ")
      leia (KM)
      escreva ("Por quantos dias o carro foi alugado? ")
      leia (DIAS)
      diasP <- dias*90
      kmP <- 0.20* km
      Escreval ("O total a pagar pelos dias alugados será: R$",diasp:5:2)
      escreval ("O total a pagar pelos KM rodados será: R$",kmP:5:2)
      
fimalgoritmo
